<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4019.2">
  <POU Name="F_Success" Id="{1f2321bb-8405-4e96-a878-5b581c40e42d}" SpecialFunc="None">
    <Declaration><![CDATA[///Checks if the returned HRESULT is success
FUNCTION F_Success : BOOL
VAR_INPUT
    hr : HRESULT;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_Success := (hr >= 0);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>